### ISSUE TITLE
GPL-3 licensed code mixed with GPL-2

### ISSUE THREAD

**Issue by tillea** [melff/memisc#63] opened 2023-03-01 08:13 UTC
Hi,
I intend to package memisc for Debian as a new precondition for the latest version of projpred.  I've assembled [this debian/copyright file](https://salsa.debian.org/r-pkg-team/r-cran-memisc/-/blob/master/debian/copyright#L25-L27) which lists a code snippet that is licensed under GPL-3 while all other code is GPL-2.  The Debian ftpmaster [pointed out](https://alioth-lists.debian.net/pipermail/r-pkg-team/2023-February/031936.html) that these are [not compatible licenses](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility).
Could you please clarify this licensing issue?
Kind regards, Andreas.

**Comment by melff** [comment] 2023-03-02 13:39
Hi Andreas,
I am happy to clarify the licensing issue. Have you any suggestions on how to proceed?
All the best,
Martin

**Comment by tillea** [comment] 2023-03-02 14:01
Hi Martin,

Am Thu, Mar 02, 2023 at 05:40:00AM -0800 schrieb Martin Elff:
> I am happy to clarify the licensing issue. Have you any suggestions on how to proceed?
Well, its probably hard to reach the copyright holder of the GPL-3 code.  Changing this to "GPL-2 or GPL-3" would be OK.  Otherwise the other code could be changed to GPL-2+ which is compatible with GPL-3.
Hope this helps, Andreas.

**Comment by melff** [comment] 2023-03-05 19:33
Would it help to change the "Licence" field in the DESCRIPTION file from "GPL-2" to "GPL-2 | GPL-3" as described in https://cran.r-project.org/doc/manuals/R-exts.html#Licensing?

**Comment by tillea** [comment] 2023-03-06 07:49
Am Sun, Mar 05, 2023 at 11:33:44AM -0800 schrieb Martin Elff:
> Would it help to change the "Licence" field in the DESCRIPTION file from "GPL-2" to "GPL-2 | GPL-3" as described in https://cran.r-project.org/doc/manuals/R-exts.html#Licensing?
Well, the most straightforward expression would be GPL-3.  That or condition in "GPL-2 | GPL-3" has one invalid part since you can't mix code of GPL-2 and GPL-3.  As long as there is a GPL-3 licensed code piece inside your software the other parts can't be licensed GPL-2.  However, GPL-2+ should be OK.
Kind regards, Andreas.

**Comment by melff** [comment] 2023-03-06 08:47
CRAN specifies "GPL-2 | GPL-3" as a possible but not "GPL-2+". Another option that the documentation offers is "GPL (>= 2)".

The problem is that some of code copied from elsewhere is GPL-2 and other code contributed is GPL-3, while the code I have written should be covered by the "Licence" field in the DESCRIPTION file. I personally am indifferent whether my code is GPL-2 or GPL-3 ...

**Comment by tillea** [comment] 2023-03-06 14:26
Am Mon, Mar 06, 2023 at 12:48:06AM -0800 schrieb Martin Elff:
> CRAN specifies "GPL-2 | GPL-3" as a possible but not "GPL-2+". Another option that the documentation offers is "GPL (>= 2)".

IMHO "GPL (>= 2)" is identical to the Debian syntax "GPL-2+".  (Please note: I'm not a CRAN contributor so I might be wrong.)
 
> The problem is that some of code copied from elsewhere is GPL-2 and other code contributed is GPL-3, while the code I have written should be covered by the "Licence" field in the DESCRIPTION file. I personally am indifferent whether my code is GPL-2 or GPL-3 ...

I perfectly understand your dilemma.  But those code copies with GPL-2 and GPL-3 are just in conflict and can not be used in one project.  Its not a matter of your DESCRIPTION file but rather of the license those third party authors have choosen.  May be you need to talk to them.  Please note that this code is not only illegal in Debian but also on CRAN.

Kind regards, Andreas.

**Comment by melff** [comment] 2023-03-06 20:55
Claims about illegality as you are making here serve only to discourage people from contributing to and redistributing free software. I hope that this is not your intention.

I am going through the items in the 'debian/copyright' file. 

Lines 15-21 in 'src/pspp-portableStream-for-R.c'  are not restricted to GPL-2. The file 'pfm-read.c' from the foreign package from which this snipped was copied contains the statement "This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, *or (at your option) any later version*." [my emphasis]

Lines 604-649 in 'dataset-methods.R' were copied and modified from lines 129-194 in file 'summary.R' from the R package 'base'. The licence notice in this file states:  "This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, *or (at your option) any later version*." [my emphasis]

Lines 18-155 in 'contrasts.R' were copied and modified from lines 46-81, 131-170 in file 'contrasts.R' from the R package 'stats'. The licence notice in this file states:  "This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, *or (at your option) any later version*." [my emphasis]
Lines 160-182 in 'contrasts.R' were copied and modified from lines 17-35 in file 'contr.sdif.R' from the R package 'MASS'. The licence notice in this file states:  "This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, *or (at your option) any later version*." [my emphasis]

File 'yy-mtable-ext-JasonWMorgan.R' was contributed as a whole by Jason Morgan under a GPL-3 or later licence.

Except for the file named last, all files GPL-2 *or later*. By the Compatibility matrix in https://www.gnu.org/licenses/gpl-faq.html there should not be an incompatibilty between code that is all GPL-2 *or* GPL-3 and code that is *GPL-3*.

I will insert the appropriate notices in the updated source of my package.

**Comment by tillea** [comment] 2023-03-06 21:19
Am Mon, Mar 06, 2023 at 12:56:06PM -0800 schrieb Martin Elff:
> Claims about illegality as you are making here serve only to discourage people from contributing to and redistributing free software. I hope that this is not your intention.

Well, its not my claim.  My intention is to distribute your code in Debian nothing else.  I was asked for clarification in the reject message of Debian ftpmaster: https://alioth-lists.debian.net/pipermail/r-pkg-team/2023-February/031936.html

> Except for the file named last, all files GPL-2 *or later*.

*Or later* would be perfectly fine - may be I misinterpreted your previous messages.

> By the Compatibility matrix in https://www.gnu.org/licenses/gpl-faq.html there should not be an incompatibilty between code that is all GPL-2 *or* GPL-3 and code that is *GPL-3*.
> 
> I will insert the appropriate notices in the updated source of my package.

This would be extremely helpful.  Thanks a lot and sorry if my words might have sounded agressive which was far from intended, Andreas.

**Comment by melff** [comment] 2023-03-07 17:49
I inserted the relevant licence statements to the code copied from elsewhere. See commit bb1257b704e23b66b5122a5dab671d79e85c1660.

I hope we can close this issue and you can prepare the Debian-package. I will submit this version very soon to CRAN as well.

All the best,
Martin

**Comment by tillea** [comment] 2023-03-07 18:00
Am Tue, Mar 07, 2023 at 09:49:26AM -0800 schrieb Martin Elff:
> I inserted the relevant licence statements to the code copied from elsewhere. See commit bb1257b704e23b66b5122a5dab671d79e85c1660.

Thanks a lot.
 
> I hope we can close this issue and you can prepare the Debian-package. I will submit this version very soon to CRAN as well.

I'm usually obtaining the code from CRAN, so I'll wait until tomorrow / day after tomorrow until it shows up there.

Kind regards
   Andreas.

**Comment by melff** [comment] 2023-03-26 19:56
Version 0.99.31.6 is on CRAN since 10 March 2023. Can we close this issue now?

Best,
Martin

**Comment by tillea** [comment] 2023-03-27 05:26
Hi Martin,

Am Sun, Mar 26, 2023 at 12:56:53PM -0700 schrieb Martin Elff:
> Version 0.99.31.6 is on CRAN since 10 March 2023. Can we close this issue now?

Thank you for your effort and the ping.  I've uploaded the Debian package right after your information and its in Debian new queue since two weeks ( https://ftp-master.debian.org/new/r-cran-memisc_0.99.31.6+dfsg-1.html ).  I think it makes sense to close this issue.  In case ftpmaster will find some other / remaining problem I can open a new issue.
Kind regards, Andreas.

**Closed** 2023-03-29 15:09 UTC
