### ISSUE TITLE
as.character(as.item(..., missing.values = 0, ...)) returns NA instead of a string

### ISSUE THREAD

**Issue by bixiou** [melff/memisc#52] opened 2021-02-08 15:00 UTC
Since an update in memisc (somewhere between 0.99.22 and 0.99.28), the following code returns an error:
```  
foo <- as.item(c(0,1,1,-1), missing.values= 0, labels = structure(c(-1,0,1), names=c('Yes', 'PNR', 'No')))
bar <- as.factor(as.character(foo))
bar <- relevel(bar, 'PNR')
```
Before the update (I had 0.99.22), we had: `foo = c('PNR', 'Yes', 'Yes', 'No')` while now we have `foo = c(NA, 'Yes', 'Yes', 'No')`.
This is a weird behavior because the point of memisc is to distinguish _missing_ values from `NA`.
Can you revert to the previous behavior?

**Comment by bixiou** [comment] 2021-02-15 22:57
PS: I corrected a typo in my post. With the typo there was no error. Now, there is the error.

**Comment by melff** [comment] 2021-02-18 16:23
This is not a bug, but a feature. Values equal to `0` are translated into `NA` by `as.character()` because `0` is marked as a missing value. Such an automatic translation into `NA` is the whole point of the `"item"` class, because otherwise there is no way in *R* to distinguish between "non-NA" missing values and `NA`.

If you want to retain "PNR" as a valid factor level, you have to declare `0` as valid.
E.g. by 
```
missing.values(foo) <- NULL
bar <- as.factor(foo)
bar <- relevel(bar, 'PNR')
```
or 
```
valid.values(foo) <- -1:1
bar <- as.factor(foo)
bar <- relevel(bar, 'PNR')
```
or
```
bar <- as.factor(include.missings(foo))
bar <- relevel(bar, 'PNR')
```

If in earlier versions of *memisc* `as.character()` did not take into account the missingness status of certain values then *that* was a bug.

**Closed by melff** 2021-02-18 16:23 UTC

**Comment by bixiou** [comment] 2021-02-18 16:29
Well, this is a pity because this "bug" was really convenient: it allowed me to run regressions without dropping data ('PNR' were considered as a response category, which it is) while allowing me to treat these 'PNR' as missing in the analysis (i.e. have 
a special status for descriptive stats, graphs...). 
So I'll keep using memisc 0.99.22 which does exactly what I need.

**Comment by melff** [comment] 2021-02-18 16:58
I think
```
bar <- as.factor(as.character(include.missings(foo)))
```
will do what you intend it to do.

**Comment by bixiou** [comment] 2021-02-18 17:04
In this particular case, yes, because I convert the variable in a factor anyway. But I noticed other parts of the code where the update causes issues, namely regressions. I'd need to transform each item variable to a factor in my regressions with the new memisc version. Easier (and more compact code) to keep the old one.
