### ISSUE TITLE
`cases` function won't recognize conditions involving `is.na()`

### ISSUE THREAD

**Issue by peiychen** [melff/memisc#56] opened 2021-05-02 23:56 UTC
I encountered a similar issue as described in this post: https://stackoverflow.com/questions/33267683/r-cases-wont-recognize-results-of-is-na

Below is the reproducible code from the original post:

```{r}
threshhold = 5
d <- sample(c(1:10, NaN), 50, replace=TRUE)
d_case <- cases(
  is.na(d) -> 0,
  d > threshhold -> 1,
  d <= threshhold -> 2
)
```
```
Warning message:
In cases(0 <- is.na(d), 1 <- d > threshhold, 2 <- d <= threshhold) :
  condition 0 <- is.na(d) is never satisfied
```
While there are some workarounds, I'd greatly appreciate it if the bug could be fixed.

**Comment by melff** [comment] 2021-05-03 17:40
This is hopefully fixed in https://github.com/melff/memisc/commit/9f39209f9e8af73390768865794890a896852f87. Can you check please?

The origin of the problem is that if `d` is NA, then `d > threshhold` and `2 <- d <= threshhold` are also `NA`. `cases()` tended to give `NA` results even though `is.na(d)` gives a valid logical value. Of course this is a bit to fussy. The warning message of course is spurious and the result of a bug.

After fixing, `d_case` will equal to `0` for observations where `d` is `NA` (unless you call `cases()` with `na.rm=FALSE`, which is a newly introduced option).

**Closed** 2021-05-24 21:42 UTC
