### ISSUE TITLE
write_html error

### ISSUE THREAD

**Issue by nalimilan** [melff/memisc#51] opened 2020-12-08 17:31 UTC
I've noticed a failure when trying to export a codebook to HTML. It turns out this can be reproduced simply by having a character variable in the data frame:
```R
> write_html(codebook(data.frame(x="a")), file="codebook.html")
Error in is.finite(x) : default method not implemented for type 'list'
```

This happens on git master too.

**Comment by melff** [comment] 2020-12-15 20:27
The problem is the consequence of a bug in the creation of codebook entries for character vectors. The bug is fixed in c1aecceec77f99bd9c13785b4d6a267fd6c44984 (release 0.99.27.3.1).

**Closed by melff** 2020-12-15 20:27 UTC
