### ISSUE TITLE
library(memisc) cause errors in TukeyHSD() ?

### ISSUE THREAD

**Issue by KKPMW** [melff/memisc#23] opened 2017-05-12 14:41 UTC
Hello. This is something I ran into while working with SPSS files.

The issue can be reproduced as follows:

    example(TukeyHSD) # works fine

    library(memisc)
    example(TukeyHSD)

    Error in FUN(X[[i]], ...) : subscript out of bounds

**Comment by melff** [comment] 2017-05-12 15:05
Hmm, looks like a bug. Thanks for reporting. I'll put this on the agenda for the next release.

**Comment by melff** [comment] 2017-07-02 21:25
It appears that a name clash is the root cause of this problem and has nothing to do with SPSS files.

The function "model.table" in the stats package creates objects with an "mtable" class attribute. 
In order to fix this I will have do some considerable refactoring of my own "mtable" code.

**Comment by melff** [comment] 2017-07-03 14:17
Fixed with f1c8736e95d5c6499eea3a6feae746f526e40c47 (release 0.99.11 on Github).

**Closed by melff** 2017-07-03 14:17 UTC
Labels: bug
